#!/usr/bin/python

import os
import sys
import fnmatch

my_path = "/app/fwerescripts"
if __name__ == "__main__":
        my_file = "/app/fwerescripts/start_stop_methods.sh"
        try:
                #my_path = my_file.resolve(strict=True)
                if os.path.isdir(my_path):
                        print("directory {0} =>: found".format(my_path))
                        for fname in os.listdir(my_path):
                                if fnmatch.fnmatch(fname,"*.txt"):
                                        print(fname)
                else:
                        print("File =>: {0} Missing".format(my_file))
        except IOError as e:
                print("System Error =>: {0}: File Missing =>: {1}".format(e, my_file))
